name: organic
favicon: null
layout_spectrum: 0.8641631649807096
typography_spectrum: 0.7087457391899079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8241656091995537
  lightness: 0.7585853848140687
  saturation: 0.3419176659081131
  rhythmicContrast: 0.732172030955553
purpose: []
